#####################################################################
############ CONFIG FILE FOR TRAINING ECOVAD FROM SCRATCH ###########
#####################################################################

########################################
#### Parameters for training ecoVAD ####
########################################

######################
# Path specification #
######################

# Path to the dataset containing the training and validation data
TRAIN_VAL_PATH: "./assets/demo_data/training_model/synthetic_dataset"

# Path to store the model weights
MODEL_SAVE_PATH: "./assets/model_weights/ecoVAD_weights_demo.pt"

# Save the checkpoints of early stopping call
CKPT_SAVE_PATH: "./assets/model_weights/ecoVAD_ckpts_demo.pt"

#########################
# Model hyperparameters #
#########################

# Learning rate
LR: 0.001

# Momentum
MOMENTUM: 0.99

# Decay
DECAY: 0.01

# Batch size to use for training
BATCH_SIZE: 32

# Number of epochs to train the model for
NUM_EPOCH: 50

##############################
# Tensorboard specifications #
##############################

# Tensorboard folder
TB_PREFIX: "demo_training"

# Comment suffix for Tensorboard run
TB_COMMENT: "no-comments"

###########################
# Hardware specifications #
###########################

# Numbers of workers, best to have num_workers = number of CPUs
NUM_WORKERS: 0

# Whether to training pipeline should use a GPU
USE_GPU: False







